name: 'PR and Commit Message Check'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Message
        uses: gsactions/commit-message-checker@16fa2d5de096ae0d35626443bcd24f1e756cafee #2.0.0
        with:
          pattern: '^(Merge .+|((feat|fix|chore|docs|style|refactor|perf|ci|test)(\(.+\))?: [A-Z0-9].+[^.\s])$)'
          error: 'Commit messages and PR title should match conventional commit convention and start with an uppercase.'
          excludeDescription: 'true'
          excludeTitle: 'false'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
